fix #1 Incorrect Access-Control-Allow-Origin header when cors option is function and no origin header is present
NozomuIkuta/h3-cors pull request #2
Opened 2022-09-07 16:06 UTC by JamieCurnow

2022-09-08 16:46 UTC, NozomuIkuta requested changes
@JamieCurnow 

Hi, thank you for reporting the bug and submitting a PR!!

While I'm reporting the upstream bug, would you add a test case for your PR?

Here is the related part: 
https://github.com/NozomuIkuta/h3-cors/blob/cc04f8579a59c053d163ca695a75ac9849bc95fc/test/utils.test.ts#L167

I appreciate if you add your test case at the end of the "describe" code block.

2022-09-08 16:46 UTC, NozomuIkuta commented on src/utils.ts
> -  const requestOriginHeader = getRequestHeader(event, 'Origin') as string
This is a bug of `getRequestHeader` function.
It returns `string | string[]` while it should return `string | string[] | undefined`.

I will create a bug report in the h3 upstream repository and add a reference to it as a comment.

---

Confession: I added the utility functions to the upstream, so it's my mistake.

2022-09-08 16:54 UTC, NozomuIkuta requested changes

2022-09-08 16:54 UTC, NozomuIkuta commented on src/utils.ts
> +  const headers = !requestOriginHeader ? '*' : Array.isArray(requestOriginHeader) ? requestOriginHeader.join(',') : requestOriginHeader
```suggestion
  // Type assertion is needed due to upstream issue: https://github.com/unjs/h3/issues/176
  const requestOriginHeader = getRequestHeader(event, 'Origin') as string | undefined
  const headers = !requestOriginHeader ? '*' : Array.isArray(requestOriginHeader) ? requestOriginHeader.join(',') : requestOriginHeader
```

2022-09-08 16:56 UTC, NozomuIkuta commented on src/utils.ts
> -  const requestOriginHeader = getRequestHeader(event, 'Origin') as string
This conversation can be resolved once https://github.com/NozomuIkuta/h3-cors/pull/2#discussion_r966198831 is resolved.

2022-09-10 10:04 UTC, NozomuIkuta commented on src/utils.ts
> +  const headers = !requestOriginHeader ? '*' : Array.isArray(requestOriginHeader) ? requestOriginHeader.join(',') : requestOriginHeader
Applied: 7c1e308dcd7e680a2ede265915006763e3809251

2022-09-10 10:10 UTC, NozomuIkuta approved these changes
I added the following changes and approve this PR.

- Fixed PR title to make commit message semantic
- Refactored the logic
- Added a unit test to cover the change

---

@JamieCurnow 

Thank you for contribution!
I will let you know when I publish the package to the npm registry!

2022-09-10 10:11 UTC, merged

2022-09-10 10:24 UTC, JamieCurnow commented
@NozomuIkuta thank you so much 👌 I was going to get around to it this weekend but you beat me to it 🙌

2022-09-10 10:39 UTC, NozomuIkuta commented
@JamieCurnow 

I have just published the package. 🙋‍♀️ 
Please check v0.1.4. 👍